services:
  arbiter:
    build: .
    container_name: arbiter
    environment:
      - PYTHONPATH=/
    volumes:
      - ./arbiter:/arbiter
      - ./examples:/examples
      - ./logs:/logs
      - ./vuln_templates:/vuln_templates
