services:
  arbiter:
    build: .
    container_name: arbiter
    volumes:
      - ./examples:/home/test/examples
      - ./logs:/home/test/logs
      - ./json_dir:/home/test/json_dir
      - ./vuln_templates:/home/test/vuln_templates
